name: Desplegar Astro a GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Configurar pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm

      - name: Instalar dependencias
        run: pnpm install

      - name: Construir
        run: pnpm run build

      - name: Desplegar a GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
